/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agarian.ui.game;

import com.agarian.main.Main;
import com.agarian.ui.MenuGUI;
import com.agarian.utils.DatabaseUtils;
import com.agarian.utils.SpacedTimer;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author crysi
 */
public class GameFrame extends javax.swing.JFrame implements MouseListener, ActionListener {

    public final GamePanel PANEL_GRID;
    public Timer timer = new Timer(1, this);
    private int time = 25000; // terrible variable name - used for time remaining until 
    private SpacedTimer spacedTimer;
    public int money = 200;
    public int level = 0;

    /**
     * Creates new form GameGUI
     */
    public GameFrame() {
        this.PANEL_GRID = new GamePanel(this);
        money = Main.money;
        level = Main.level;
        initComponents();
        jPanel1.add(PANEL_GRID);
        jLabelBalance.setText("" + money);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelInfoBar = new javax.swing.JPanel();
        jPanelExit = new javax.swing.JPanel();
        jLabelXIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBalance = new javax.swing.JLabel();
        jLabelTimeRemaining = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelHealth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 450));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jPanelInfoBar.setBackground(new java.awt.Color(0, 139, 230));
        jPanelInfoBar.setEnabled(false);
        jPanelInfoBar.setFocusable(false);
        jPanelInfoBar.setPreferredSize(new java.awt.Dimension(810, 54));

        jPanelExit.setBackground(new java.awt.Color(255, 255, 255));
        jPanelExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanelExit.addMouseListener(this);

        jLabelXIcon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelXIcon.setText("X");

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelXIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelXIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Balance:");

        jLabelBalance.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabelBalance.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBalance.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelBalance.setText("0");

        jLabelTimeRemaining.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTimeRemaining.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Level:");

        jLabelLevel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabelLevel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLevel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelLevel.setText("0");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HQ Health:");

        jLabelHealth.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabelHealth.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHealth.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelHealth.setText("0");

        javax.swing.GroupLayout jPanelInfoBarLayout = new javax.swing.GroupLayout(jPanelInfoBar);
        jPanelInfoBar.setLayout(jPanelInfoBarLayout);
        jPanelInfoBarLayout.setHorizontalGroup(
            jPanelInfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanelInfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInfoBarLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInfoBarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabelTimeRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelInfoBarLayout.setVerticalGroup(
            jPanelInfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelHealth))
            .addComponent(jLabelTimeRemaining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelInfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelInfoBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoBarLayout.createSequentialGroup()
                        .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBalance)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInfoBar, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelInfoBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelExit) {
            GameFrame.this.jPanelExitMouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelExit) {
            GameFrame.this.jPanelExitMouseEntered(evt);
        }
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelExit) {
            GameFrame.this.jPanelExitMouseExited(evt);
        }
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseClicked
        try {
            // TODO add your handling code here:
            new MenuGUI().setVisible(true);
            DatabaseUtils db = new DatabaseUtils();
            db.save(Main.username, money, level, PANEL_GRID.hqHealth, GamePanel.creatures, GamePanel.turrets).end();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanelExitMouseClicked

    private void jPanelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseEntered
        // TODO add your handling code here:
        jPanelExit.setBackground(Color.red);
        jLabelXIcon.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanelExitMouseEntered

    private void jPanelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseExited
        // TODO add your handling code here:
        jPanelExit.setBackground(Color.WHITE);
        jLabelXIcon.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPanelExitMouseExited

    public void setHQHealth(int health) {
        jLabelHealth.setText(health + "");
    }

    public void addMoney(int amount) {
        money += amount; //Short hand for money = money + amount
        jLabelBalance.setText("" + money);
    }

    public void removeMoney(int amount) {
        money -= amount;
        jLabelBalance.setText("" + money);
    }

    public int getMoney() {
        return money;
    }

    public int getLevel() {
        return level;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBalance;
    private javax.swing.JLabel jLabelHealth;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelTimeRemaining;
    private javax.swing.JLabel jLabelXIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JPanel jPanelInfoBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        jLabelTimeRemaining.setText("Time remaining: " + time);
        time -= 100;
        if (time == 0) {
            time = 25000;
            level++;
            jLabelTimeRemaining.setText("");
            spacedTimer = new SpacedTimer(PANEL_GRID, level + 1);
            spacedTimer.startTimer();
            jLabelLevel.setText(level + "");
            timer.stop();
        }
    }
}
