/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agarian.ui;

import com.agarian.main.Main;
import com.agarian.utils.DatabaseUtils;
import java.awt.EventQueue;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author crysi
 */
public class LoginGUI extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsername = new javax.swing.JTextField();
        jPanelHeader = new javax.swing.JPanel();
        jLabelLoginCreate = new javax.swing.JLabel();
        jPanelLoginButton = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextFieldUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jPanelHeader.setBackground(new java.awt.Color(51, 51, 51));

        jLabelLoginCreate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelLoginCreate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoginCreate.setText("Login Or Create a profile");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLoginCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLoginCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLoginButton.setBackground(new java.awt.Color(0, 123, 217));
        jPanelLoginButton.addMouseListener(this);

        jLabelLogin.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setText("LOGIN");

        javax.swing.GroupLayout jPanelLoginButtonLayout = new javax.swing.GroupLayout(jPanelLoginButton);
        jPanelLoginButton.setLayout(jPanelLoginButtonLayout);
        jPanelLoginButtonLayout.setHorizontalGroup(
            jPanelLoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLoginButtonLayout.setVerticalGroup(
            jPanelLoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setText("USERNAME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldUsername))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jPanelLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 184, Short.MAX_VALUE))
                    .addComponent(jLabelUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jPanelLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelLoginButton) {
            LoginGUI.this.jPanelLoginButtonMouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelLoginButton) {
            LoginGUI.this.jPanelLoginButtonMouseEntered(evt);
        }
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelLoginButton) {
            LoginGUI.this.jPanelLoginButtonMouseExited(evt);
        }
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelLoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLoginButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelLoginButtonMouseEntered

    private void jPanelLoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLoginButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelLoginButtonMouseExited

    private void jPanelLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLoginButtonMouseClicked
        // TODO add your handling code here:
        try {
            String enteredUsername = jTextFieldUsername.getText();
            if (!enteredUsername.isEmpty()) {
                DatabaseUtils database = new DatabaseUtils();
                List<String> usernames = database.getUsernames();
                //Don't really care about security
                boolean usernameCorrect = false;
                for (int o = 0; o < usernames.size(); o++) {
                    if (enteredUsername.toLowerCase().equals(usernames.get(o).toLowerCase())) {
                        usernameCorrect = true;
                    }
                }
                if (usernameCorrect) {
                    int[] info = database.getUserInfo(enteredUsername);
                    Main.turrets = database.getTurrets(enteredUsername);
                    Main.creatures = database.getCreatures(enteredUsername);
                    Main.level = info[1];
                    Main.money = info[0];
                    Main.username = enteredUsername;
                    EventQueue.invokeLater(() -> new MenuGUI().setVisible(true));
                } else if (!usernameCorrect) {
                    database.createProfile(enteredUsername);
                    Main.level = 0;
                    Main.money = 150;
                    Main.username = enteredUsername;
                    EventQueue.invokeLater(() -> new MenuGUI().setVisible(true));
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a name!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please close all other instances of the game!");
        }
    }//GEN-LAST:event_jPanelLoginButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLoginCreate;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLoginButton;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
