/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agarian.ui;

import com.agarian.ui.game.GameFrame;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;

/**
 *
 * @author crysi
 */
public class MenuGUI extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBody = new javax.swing.JPanel();
        jPanelSinglePlayer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelSandbox = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelHelp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelExit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agarian Defence");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanelBody.setBackground(new java.awt.Color(102, 102, 102));
        jPanelBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanelSinglePlayer.setName("singleplayer"); // NOI18N
        jPanelSinglePlayer.addMouseListener(this);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Singleplayer");

        javax.swing.GroupLayout jPanelSinglePlayerLayout = new javax.swing.GroupLayout(jPanelSinglePlayer);
        jPanelSinglePlayer.setLayout(jPanelSinglePlayerLayout);
        jPanelSinglePlayerLayout.setHorizontalGroup(
            jPanelSinglePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSinglePlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSinglePlayerLayout.setVerticalGroup(
            jPanelSinglePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSinglePlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSandbox.setName("unsupported"); // NOI18N
        jPanelSandbox.addMouseListener(this);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sandbox");

        javax.swing.GroupLayout jPanelSandboxLayout = new javax.swing.GroupLayout(jPanelSandbox);
        jPanelSandbox.setLayout(jPanelSandboxLayout);
        jPanelSandboxLayout.setHorizontalGroup(
            jPanelSandboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSandboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSandboxLayout.setVerticalGroup(
            jPanelSandboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSandboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelHelp.setName("help"); // NOI18N
        jPanelHelp.addMouseListener(this);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Help");

        javax.swing.GroupLayout jPanelHelpLayout = new javax.swing.GroupLayout(jPanelHelp);
        jPanelHelp.setLayout(jPanelHelpLayout);
        jPanelHelpLayout.setHorizontalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHelpLayout.setVerticalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelExit.addMouseListener(this);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Exit");

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSinglePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSandbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSinglePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSandbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jPanelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jLabelTitle.setBackground(new java.awt.Color(60, 60, 60));
        jLabelTitle.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Agarian Defence");
        jLabelTitle.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelSinglePlayer) {
            MenuGUI.this.jPanelGame(evt);
        }
        else if (evt.getSource() == jPanelSandbox) {
            MenuGUI.this.jPanelGame(evt);
        }
        else if (evt.getSource() == jPanelHelp) {
            MenuGUI.this.jPanelGame(evt);
        }
        else if (evt.getSource() == jPanelExit) {
            MenuGUI.this.jPanelExitClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelSinglePlayer) {
            MenuGUI.this.jPanelEntered(evt);
        }
        else if (evt.getSource() == jPanelSandbox) {
            MenuGUI.this.jPanelEntered(evt);
        }
        else if (evt.getSource() == jPanelHelp) {
            MenuGUI.this.jPanelEntered(evt);
        }
        else if (evt.getSource() == jPanelExit) {
            MenuGUI.this.jPanelEntered(evt);
        }
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanelSinglePlayer) {
            MenuGUI.this.jPanelExited(evt);
        }
        else if (evt.getSource() == jPanelSandbox) {
            MenuGUI.this.jPanelExited(evt);
        }
        else if (evt.getSource() == jPanelHelp) {
            MenuGUI.this.jPanelExited(evt);
        }
        else if (evt.getSource() == jPanelExit) {
            MenuGUI.this.jPanelExited(evt);
        }
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelExitClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanelExitClicked

    private void jPanelEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEntered
        // TODO add your handling code here:
        evt.getComponent().setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanelEntered

    private void jPanelExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExited
        // TODO add your handling code here:
        evt.getComponent().setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_jPanelExited

    private void jPanelGame(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGame
        // TODO add your handling code here:
        if (evt.getComponent().getName().equals("singleplayer")) {
            EventQueue.invokeLater(() -> new GameFrame().setVisible(true));
            this.dispose();
        } else if (evt.getComponent().getName().equals("help")) {
            EventQueue.invokeLater(() -> new HelpGUI().setVisible(true));
        } else {
            JOptionPane.showMessageDialog(this, "Unsupported Function!");
        }
    }//GEN-LAST:event_jPanelGame


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JPanel jPanelHelp;
    private javax.swing.JPanel jPanelSandbox;
    private javax.swing.JPanel jPanelSinglePlayer;
    // End of variables declaration//GEN-END:variables
}
